import type { Metadata } from 'next';

// react slick 라이브러리 css
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

// react toastify 라이브러리 css
// import 'react-toastify/dist/ReactToastify.css';

import '@/styles/global.scss';
import '@/styles/bottom-sheet.scss';

import Header from '@/components/global/header';
import ClientApplication from './clientApplication';
import Footer from '@/components/global/footer';

import { ToastContainer } from 'react-toastify';

declare global {
  interface Window {
    gtag?: any;
  }
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// const DEFAULT_SEO = {
//   title: '웹툰투데이ㅣ여기저기 흩어진 웹툰 정보를 한눈에',
//   description: '지금 봐야 무료인 네이버, 카카오 웹툰 정보도 알려드려요!',
//   canonical: 'https://www.todaytoon.me',
//   openGraph: {
//     type: 'website',
//     locale: 'ko_KR',
//     url: 'https://www.todaytoon.me',
//     title: '웹툰투데이ㅣ여기저기 흩어진 웹툰 정보를 한눈에',
//     site_name: '웹툰투데이',
//     images: [
//       {
//         url: 'https://ifh.cc/g/6FyVQj.png',
//         width: 128,
//         height: 128,
//         alt: '웹툰투데이_로고',
//       },
//     ],
//   },
//   twitter: {
//     handle: '@handle',
//     site: '@site',
//     cardType: 'summary_large_image',
//   },
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap" rel="stylesheet" />

        <script defer src="https://developers.kakao.com/sdk/js/kakao.min.js"></script>

        {/* <script
          dangerouslySetInnerHTML={{
            __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', '${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}', {
              page_path: window.location.pathname,
            });
          `,
          }}
        /> */}

        {/* <script async src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}`}></script> */}
        {/* <script async src="https://www.googleoptimize.com/optimize.js?id=OPT-TGCBRJD"></script> */}
        <title>웹툰투데이</title>
      </head>

      <body>
        <ClientApplication>
          {/* <DefaultSeo {...DEFAULT_SEO} /> */}

          <div className="global-wrapper">
            <Header />

            {children}

            <Footer />

            <ToastContainer />
          </div>
        </ClientApplication>
      </body>
    </html>
  );
}
